import React, { useState } from "react";
import { ContentItem } from "../types";
import {
  X,
  Copy,
  Check,
  Download,
  CheckCircle2,
  Sparkles,
  FileText,
  Globe,
} from "lucide-react";

interface PublishReadyModalProps {
  item: ContentItem | null;
  isOpen: boolean;
  onClose: () => void;
  onMarkPublished: (itemId: string) => void;
  onToggleEnglish?: (itemId: string, include: boolean) => void;
}

export const PublishReadyModal: React.FC<PublishReadyModalProps> = ({
  item,
  isOpen,
  onClose,
  onMarkPublished,
  onToggleEnglish,
}) => {
  const [copiedType, setCopiedType] = useState<string | null>(null);
  const [languageMode, setLanguageMode] = useState<"bilingual" | "kr" | "en">(
    item?.includeEnglish ? "bilingual" : "kr"
  );

  if (!isOpen || !item) return null;

  const krText =
    item.channel === "Threads"
      ? item.copywriting?.threadsText || item.copywriting?.feedText || ""
      : item.copywriting?.feedText || "";

  const enText =
    item.channel === "Threads"
      ? item.copywriting?.threadsTextEn || item.copywriting?.feedTextEn || ""
      : item.copywriting?.feedTextEn || "";

  let masterText = krText;
  if (languageMode === "bilingual") {
    if (enText) {
      masterText = `${krText}\n\n---\n\n[English Version]\n${enText}`;
    } else {
      masterText = krText;
    }
  } else if (languageMode === "en") {
    masterText = enText || "(영문 버전이 아직 생성되지 않았습니다)";
  }

  const allHashtags = [
    ...(item.hashtags || []),
    ...(languageMode !== "kr" && item.copywriting?.hashtagsEn
      ? item.copywriting.hashtagsEn
      : []),
  ];

  const fullUploadPayload = `${masterText}\n\n${allHashtags.join(" ")}`;

  const handleCopy = (text: string, type: string) => {
    navigator.clipboard.writeText(text);
    setCopiedType(type);
    setTimeout(() => setCopiedType(null), 2000);
  };

  const handleDownloadMD = () => {
    const mdContent = `# [최종 게시본] ${item.topic}
- 채널: ${item.channel}
- 게시 날짜: ${item.date} (${item.dayOfWeek})
- 콘텐츠 종류: ${item.contentType}
- 3대 층위: ${item.depthLayer}
- 영문 포함 여부: ${item.includeEnglish ? "포함 (Bilingual/English)" : "미포함 (Korean Only)"}

---

## 1. 게시글 본문 (${languageMode === "bilingual" ? "한·영 병기" : languageMode === "en" ? "영문" : "한국어"})
${masterText}

---

## 2. 추천 해시태그
${allHashtags.join(" ")}

---

## 3. 이미지 / 비주얼 제작 가이드
- 공간: ${item.visualDirection?.space}
- 소품: ${item.visualDirection?.props}
- 조명: ${item.visualDirection?.lighting}
- 구도: ${item.visualDirection?.composition}
- 비율: ${item.visualDirection?.aspectRatio}
- 이미지 내 텍스트: ${item.visualDirection?.overlayText || "없음"}
- AI 프롬프트: ${item.visualDirection?.promptEn || "없음"}

---
* Generated by Lifestyle Brand Content Director Studio
`;

    const blob = new Blob([mdContent], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Publish_${item.date}_${item.channel.replace(/\s+/g, "_")}.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 bg-neutral-900/60 backdrop-blur-xs flex items-center justify-center p-3 sm:p-6 overflow-y-auto">
      <div
        id="publish-ready-dialog"
        className="bg-white rounded-2xl shadow-xl max-w-2xl w-full max-h-[92vh] flex flex-col border border-neutral-200/90 overflow-hidden"
      >
        {/* Header */}
        <div className="px-5 sm:px-6 py-4 border-b border-neutral-200/80 bg-neutral-900 text-neutral-100 flex items-center justify-between">
          <div className="flex items-center space-x-2.5 min-w-0">
            <div className="p-1.5 bg-neutral-800 rounded-lg border border-neutral-700 text-amber-300 font-bold shrink-0">
              <Sparkles className="w-4 h-4" strokeWidth={1.75} />
            </div>
            <div className="min-w-0">
              <div className="flex items-center space-x-1.5 truncate">
                <span className="text-[10px] sm:text-[11px] font-mono font-bold bg-neutral-800 px-2 py-0.5 rounded text-amber-300 border border-neutral-700 shrink-0">
                  FINAL
                </span>
                <span className="text-[11px] sm:text-xs text-neutral-300 font-medium truncate">
                  {item.channel}
                </span>
              </div>
              <h2 className="text-sm sm:text-base font-bold text-white mt-0.5 truncate tracking-tight">
                최종 게시용 콘텐츠 정리
              </h2>
            </div>
          </div>

          <button
            onClick={onClose}
            className="text-neutral-400 hover:text-white p-1.5 rounded-lg hover:bg-neutral-800 transition-colors shrink-0 ml-2"
          >
            <X className="w-5 h-5" strokeWidth={1.75} />
          </button>
        </div>

        {/* Content Body */}
        <div className="p-5 sm:p-6 overflow-y-auto space-y-4 sm:space-y-5 text-xs sm:text-sm text-neutral-800">
          {/* Metadata Row */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5 text-xs bg-neutral-50 rounded-xl p-3 border border-neutral-200/80">
            <div>
              <span className="text-neutral-500 text-[10px] block">게시 예정일</span>
              <strong className="text-neutral-900 font-mono text-[11px] sm:text-xs font-semibold">
                {item.date} ({item.dayOfWeek})
              </strong>
            </div>
            <div>
              <span className="text-neutral-500 text-[10px] block">채널</span>
              <strong className="text-neutral-900 text-[11px] sm:text-xs font-semibold">{item.channel}</strong>
            </div>
            <div>
              <span className="text-neutral-500 text-[10px] block">콘텐츠 종류</span>
              <strong className="text-neutral-900 text-[11px] sm:text-xs font-semibold">{item.contentType}</strong>
            </div>
            <div>
              <span className="text-neutral-500 text-[10px] block">현재 상태</span>
              <strong className="text-neutral-900 font-semibold text-[11px] sm:text-xs">{item.status}</strong>
            </div>
          </div>

          {/* Language Selection Bar */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2.5 p-3 bg-neutral-100/70 rounded-xl border border-neutral-200/80 text-xs">
            <div className="flex items-center space-x-2">
              <Globe className="w-3.5 h-3.5 sm:w-4 sm:h-4 text-neutral-700 shrink-0" strokeWidth={1.75} />
              <span className="font-semibold text-neutral-800 text-[11px] sm:text-xs">영문 포함 모드:</span>
              <span className="text-neutral-600 text-[11px]">
                {item.includeEnglish ? "포함 (ON)" : "미포함 (OFF)"}
              </span>
            </div>

            <div className="flex items-center space-x-1 bg-white rounded-lg border border-neutral-200 p-0.5 self-start sm:self-auto shrink-0 shadow-2xs">
              <button
                onClick={() => setLanguageMode("bilingual")}
                className={`px-2.5 py-1 text-xs font-semibold rounded-md transition-colors ${
                  languageMode === "bilingual"
                    ? "bg-neutral-900 text-white shadow-2xs"
                    : "text-neutral-600 hover:text-neutral-900 hover:bg-neutral-50"
                }`}
              >
                한·영 병기
              </button>
              <button
                onClick={() => setLanguageMode("kr")}
                className={`px-2.5 py-1 text-xs font-semibold rounded-md transition-colors ${
                  languageMode === "kr"
                    ? "bg-neutral-900 text-white shadow-2xs"
                    : "text-neutral-600 hover:text-neutral-900 hover:bg-neutral-50"
                }`}
              >
                한국어
              </button>
              <button
                onClick={() => setLanguageMode("en")}
                className={`px-2.5 py-1 text-xs font-semibold rounded-md transition-colors ${
                  languageMode === "en"
                    ? "bg-neutral-900 text-white shadow-2xs"
                    : "text-neutral-600 hover:text-neutral-900 hover:bg-neutral-50"
                }`}
              >
                영문
              </button>
            </div>
          </div>

          {/* Topic */}
          <div>
            <span className="text-xs font-semibold text-neutral-500 block mb-1">
              콘텐츠 주제
            </span>
            <p className="font-bold text-neutral-900 text-sm sm:text-base tracking-tight">
              {item.topic}
            </p>
          </div>

          {/* Master Ready-to-copy Caption */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-neutral-800 flex items-center space-x-1.5">
                <FileText className="w-3.5 h-3.5 text-neutral-600" strokeWidth={1.75} />
                <span>업로드용 완성형 게시글 본문</span>
              </span>
              <button
                onClick={() => handleCopy(fullUploadPayload, "full")}
                className="flex items-center space-x-1.5 px-3 py-1.5 bg-neutral-900 text-white hover:bg-neutral-800 text-xs font-medium rounded-xl shadow-2xs transition-colors"
              >
                {copiedType === "full" ? (
                  <Check className="w-3.5 h-3.5 text-emerald-300" strokeWidth={2} />
                ) : (
                  <Copy className="w-3.5 h-3.5" strokeWidth={1.75} />
                )}
                <span>{copiedType === "full" ? "복사 완료!" : "본문+태그 전체 복사"}</span>
              </button>
            </div>

            <div className="p-4 bg-neutral-50/80 rounded-xl border border-neutral-200 text-xs sm:text-sm text-neutral-800 leading-relaxed whitespace-pre-wrap select-all">
              {masterText}
            </div>
          </div>

          {/* Hashtags */}
          <div className="space-y-1.5">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold text-neutral-700">해시태그</span>
              <button
                onClick={() =>
                  handleCopy(allHashtags.join(" "), "tags")
                }
                className="text-[11px] font-medium text-neutral-600 hover:text-neutral-900 transition-colors"
              >
                {copiedType === "tags" ? "✓ 복사됨" : "해시태그 복사"}
              </button>
            </div>
            <div className="p-3 bg-neutral-50/80 rounded-xl border border-neutral-200 text-xs text-neutral-700 font-mono">
              {allHashtags.join(" ")}
            </div>
          </div>

          {/* Visual Specs & Attached Image */}
          <div className="p-5 bg-neutral-900 text-neutral-100 space-y-3.5 rounded-2xl border border-neutral-800 shadow-sm">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-amber-300 block">
                📸 이미지 / 영상 최종 비주얼
              </span>
              {item.imageUrl && (
                <span className="text-[10px] font-mono px-2 py-0.5 bg-neutral-800 rounded-md border border-neutral-700 text-neutral-300">
                  {item.imageSource === "upload"
                    ? "📁 직접 업로드됨"
                    : item.imageSource === "ai"
                    ? "✨ AI 생성 비주얼"
                    : "🖼️ 감성 프리셋"}
                </span>
              )}
            </div>

            {/* If Image or Video exists, render visual frame */}
            {item.imageUrl && (
              <div className="relative overflow-hidden bg-black rounded-xl border border-neutral-800 max-h-72 flex items-center justify-center group">
                {item.mediaType === "video" || /\.(mp4|webm|mov|m4v)/i.test(item.imageUrl) ? (
                  <video
                    src={item.imageUrl}
                    controls
                    autoPlay
                    loop
                    muted
                    playsInline
                    className="w-full max-h-72 object-contain bg-black"
                  />
                ) : (
                  <img
                    src={item.imageUrl}
                    alt={item.topic}
                    referrerPolicy="no-referrer"
                    className="w-full h-56 object-cover object-center"
                  />
                )}
                <div className="absolute top-2 right-2 flex items-center space-x-1">
                  <a
                    href={item.imageUrl}
                    download={
                      item.imageFileName ||
                      `publish-visual-${item.date}.${
                        item.mediaType === "video" || /\.(mp4|webm|mov|m4v)/i.test(item.imageUrl)
                          ? "mp4"
                          : "png"
                      }`
                    }
                    target="_blank"
                    rel="noreferrer"
                    className="flex items-center space-x-1.5 px-3 py-1.5 bg-neutral-900/90 hover:bg-neutral-800 text-white text-[11px] font-semibold rounded-lg border border-neutral-700 backdrop-blur-xs transition-colors shadow-2xs"
                  >
                    <Download className="w-3 h-3 text-amber-300" strokeWidth={1.75} />
                    <span>
                      {item.mediaType === "video" || /\.(mp4|webm|mov|m4v)/i.test(item.imageUrl)
                        ? "동영상 파일 받기"
                        : "이미지 파일 받기"}
                    </span>
                  </a>
                </div>
              </div>
            )}

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5 text-xs text-neutral-300">
              <div>
                <span className="text-neutral-400 text-[10px] block">공간 및 연출:</span>
                <span>{item.visualDirection?.space}</span>
              </div>
              <div>
                <span className="text-neutral-400 text-[10px] block">조명 및 무드:</span>
                <span>{item.visualDirection?.lighting}</span>
              </div>
              <div>
                <span className="text-neutral-400 text-[10px] block">소품 및 구도:</span>
                <span>{item.visualDirection?.props}</span>
              </div>
              <div>
                <span className="text-neutral-400 text-[10px] block">권장 비율:</span>
                <span className="font-mono font-bold text-amber-200">
                  {item.visualDirection?.aspectRatio || "4:5"}
                </span>
              </div>
            </div>

            {item.visualDirection?.overlayText && (
              <div className="pt-2.5 border-t border-neutral-800 flex items-center justify-between text-xs">
                <span>
                  💬 <strong>이미지 위 문구:</strong> "{item.visualDirection.overlayText}"
                </span>
                <button
                  onClick={() =>
                    handleCopy(item.visualDirection.overlayText || "", "overlay")
                  }
                  className="text-[11px] text-amber-300 hover:underline"
                >
                  {copiedType === "overlay" ? "✓" : "복사"}
                </button>
              </div>
            )}
          </div>
        </div>

        {/* Footer Actions */}
        <div className="px-6 py-4 border-t border-neutral-200/80 bg-neutral-50 flex items-center justify-between">
          <button
            onClick={handleDownloadMD}
            className="flex items-center space-x-1.5 px-3.5 py-2 border border-neutral-200 rounded-xl bg-white text-neutral-700 hover:bg-neutral-50 text-xs font-medium transition-colors shadow-2xs"
          >
            <Download className="w-3.5 h-3.5" strokeWidth={1.75} />
            <span>.MD 파일 다운로드</span>
          </button>

          <div className="flex items-center space-x-2">
            <button
              onClick={onClose}
              className="px-4 py-2 rounded-xl text-neutral-600 hover:bg-neutral-200/60 text-xs font-medium transition-colors"
            >
              닫기
            </button>
            <button
              onClick={() => {
                onMarkPublished(item.id);
                onClose();
              }}
              className="flex items-center space-x-1.5 px-4 py-2 rounded-xl bg-neutral-900 text-white hover:bg-neutral-800 text-xs font-semibold shadow-xs transition-colors"
            >
              <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" strokeWidth={1.75} />
              <span>게시 완료로 변경</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
